<a href="https://colab.research.google.com/github/aprajeeta10/python-projects/blob/main/Credit_Risk_Modeling_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NOTE: This is a credit risk modelling project, aimed at building a scorecard to reject or accept loan candidates based on past datasets. Please note, this is a running project. Expected to be finished towards the end of January 2023.

Credits: Credit Risk Modeling in Python (Udemy)

IMPORT LIBRARIES

In [ ]:
import numpy as np
import pandas as pd
## importing two basic libraries

DATA PRE-PROCESSING

In [ ]:
loan_data_backup = pd.read_csv('loan_data_2007_2014.csv')
##creating a copy of the orginial file

In [ ]:
print(loan_data_backup)

      Unnamed: 0       id  member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
0              0  1077501    1296599       5000         5000           4975.0
1              1  1077430    1314167       2500         2500           2500.0
2              2  1077175    1313524       2400         2400           2400.0
3              3  1076863    1277178      10000        10000          10000.0
4              4  1075358    1311748       3000         3000           3000.0
...          ...      ...        ...        ...          ...              ...
1748        1748  1046552    1277600      15000        15000          14975.0
1749        1749   623231     798733       5000         5000           5000.0
1750        1750  1040347    1270317       8875         8875           8875.0
1751        1751  1046653    1277507       8000         8000           8000.0
1752        1752  1046531    1277577       4500         4500           4500.0

            term  int_rate  installment grade  ... total_bal_il il_util  \
0      36 months     10.65       162.87     B  ...          NaN     NaN
1      60 months     15.27        59.83     C  ...          NaN     NaN
2      36 months     15.96        84.33     C  ...          NaN     NaN
3      36 months     13.49       339.31     C  ...          NaN     NaN
4      60 months     12.69        67.79     B  ...          NaN     NaN
...          ...       ...          ...   ...  ...          ...     ...
1748   36 months     22.35       575.58     F  ...          NaN     NaN
1749   36 months     12.69       167.73     B  ...          NaN     NaN
1750   36 months     14.65       306.14     C  ...          NaN     NaN
1751   36 months      9.91       257.80     B  ...          NaN     NaN
1752   36 months     14.27       154.40     C  ...          NaN     NaN

     open_rv_12m open_rv_24m  max_bal_bc all_util total_rev_hi_lim inq_fi  \
0            NaN         NaN         NaN      NaN              NaN    NaN
1            NaN         NaN         NaN      NaN              NaN    NaN
2            NaN         NaN         NaN      NaN              NaN    NaN
3            NaN         NaN         NaN      NaN              NaN    NaN
4            NaN         NaN         NaN      NaN              NaN    NaN
...          ...         ...         ...      ...              ...    ...
1748         NaN         NaN         NaN      NaN              NaN    NaN
1749         NaN         NaN         NaN      NaN              NaN    NaN
1750         NaN         NaN         NaN      NaN              NaN    NaN
1751         NaN         NaN         NaN      NaN              NaN    NaN
1752         NaN         NaN         NaN      NaN              NaN    NaN

     total_cu_tl inq_last_12m
0            NaN          NaN
1            NaN          NaN
2            NaN          NaN
3            NaN          NaN
4            NaN          NaN
...          ...          ...
1748         NaN          NaN
1749         NaN          NaN
1750         NaN          NaN
1751         NaN          NaN
1752         NaN          NaN

[1753 rows x 75 columns]

In [ ]:
loan_data = loan_data_backup.copy()

In [ ]:
loan_data

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1748,1748,1046552,1277600,15000,15000,14975.0,36 months,22.35,575.58,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1749,1749,623231,798733,5000,5000,5000.0,36 months,12.69,167.73,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1750,1750,1040347,1270317,8875,8875,8875.0,36 months,14.65,306.14,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1751,1751,1046653,1277507,8000,8000,8000.0,36 months,9.91,257.80,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1752,1752,1046531,1277577,4500,4500,4500.0,36 months,14.27,154.40,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd.options.display.max_columns = None
##for better display

In [ ]:
loan_data

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.0000,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.1100,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.0000,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.0,0.0,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.0000,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.0000,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1748,1748,1046552,1277600,15000,15000,14975.0,36 months,22.35,575.58,F,F5,United States Postal Service,10+ years,RENT,67000.0,Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation Loan,100xx,NY,17.57,2.0,Nov-99,1.0,15.0,NaN,3.0,0.0,9984,99.8,26.0,f,0.0,0.0,15214.980000,15189.80,9299.72,5089.49,0.00,825.77,8.2577,Feb-14,36.80,NaN,Jun-14,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1749,1749,623231,798733,5000,5000,5000.0,36 months,12.69,167.73,B,B5,Northern Trust,3 years,MORTGAGE,142000.0,Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 11/28/11 > I had a promoti...,debt_consolidation,Refinance high interest credit card,605xx,IL,13.28,0.0,Feb-90,1.0,NaN,NaN,11.0,0.0,32945,53.3,22.0,f,0.0,0.0,5025.250000,5025.25,3858.78,985.63,0.00,180.84,1.6108,May-14,167.73,NaN,Oct-14,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1750,1750,1040347,1270317,8875,8875,8875.0,36 months,14.65,306.14,C,C3,Cross Country Staffing,< 1 year,RENT,33000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,wedding,For a Dream Wedding,331xx,FL,21.16,3.0,Jul-06,1.0,12.0,NaN,18.0,0.0,3971,41.8,29.0,f,0.0,0.0,9998.440000,9998.44,8875.00,1123.44,0.00,0.00,0.0000,Aug-13,687.57,NaN,Jan-16,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1751,1751,1046653,1277507,8000,8000,8000.0,36 months,9.91,257.80,B,B1,kade,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,moving,new start,153xx,PA,3.88,0.0,Mar-04,4.0,NaN,NaN,4.0,0.0,273,18.2,6.0,f,0.0,0.0,7495.280000,7495.28,5998.88,1203.40,0.00,293.00,2.7688,Apr-14,257.80,NaN,Sep-14,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1752,1752,1046531,1277577,4500,4500,4500.0,36 months,14.27,154.40,C,C2,Sherwin-Williams,10+ years,RENT,55000.0,Not Verified,Nov-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 11/28/11 > I plan to use t...,debt_consolidation,Debt Consolidation Loan,327xx,FL,18.92,1.0,Jul-93,2.0,7.0,NaN,16.0,0.0,10637,66.8,26.0,f,0.0,0.0,4211.990000,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
loan_data.head()
## the first five entries

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.0,0.0,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.0,0.0,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.0,0.0,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.9,766.9,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
loan_data.tail()
## the last five entries

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
1748,1748,1046552,1277600,15000,15000,14975.0,36 months,22.35,575.58,F,F5,United States Postal Service,10+ years,RENT,67000.0,Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt Consolidation Loan,100xx,NY,17.57,2.0,Nov-99,1.0,15.0,NaN,3.0,0.0,9984,99.8,26.0,f,0.0,0.0,15214.98,15189.80,9299.72,5089.49,0.0,825.77,8.2577,Feb-14,36.80,NaN,Jun-14,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1749,1749,623231,798733,5000,5000,5000.0,36 months,12.69,167.73,B,B5,Northern Trust,3 years,MORTGAGE,142000.0,Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 11/28/11 > I had a promoti...,debt_consolidation,Refinance high interest credit card,605xx,IL,13.28,0.0,Feb-90,1.0,NaN,NaN,11.0,0.0,32945,53.3,22.0,f,0.0,0.0,5025.25,5025.25,3858.78,985.63,0.0,180.84,1.6108,May-14,167.73,NaN,Oct-14,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1750,1750,1040347,1270317,8875,8875,8875.0,36 months,14.65,306.14,C,C3,Cross Country Staffing,< 1 year,RENT,33000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,wedding,For a Dream Wedding,331xx,FL,21.16,3.0,Jul-06,1.0,12.0,NaN,18.0,0.0,3971,41.8,29.0,f,0.0,0.0,9998.44,9998.44,8875.00,1123.44,0.0,0.00,0.0000,Aug-13,687.57,NaN,Jan-16,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1751,1751,1046653,1277507,8000,8000,8000.0,36 months,9.91,257.80,B,B1,kade,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,NaN,moving,new start,153xx,PA,3.88,0.0,Mar-04,4.0,NaN,NaN,4.0,0.0,273,18.2,6.0,f,0.0,0.0,7495.28,7495.28,5998.88,1203.40,0.0,293.00,2.7688,Apr-14,257.80,NaN,Sep-14,0.0,NaN,1.0,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1752,1752,1046531,1277577,4500,4500,4500.0,36 months,14.27,154.40,C,C2,Sherwin-Williams,10+ years,RENT,55000.0,Not Verified,Nov-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 11/28/11 > I plan to use t...,debt_consolidation,Debt Consolidation Loan,327xx,FL,18.92,1.0,Jul-93,2.0,7.0,NaN,16.0,0.0,10637,66.8,26.0,f,0.0,0.0,4211.99,4.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
loan_data.columns.values

array(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership',
       'annual_inc', 'verification_status', 'issue_d', 'loan_status',
       'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code',
       'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
       'recoveries', 'collection_recovery_fee', 'last_pymnt_d',
       'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m'],
      dtype=object)

In [ ]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1753 entries, 0 to 1752
Data columns (total 75 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   1753 non-null   int64
 1   id                           1753 non-null   int64
 2   member_id                    1753 non-null   int64
 3   loan_amnt                    1753 non-null   int64
 4   funded_amnt                  1753 non-null   int64
 5   funded_amnt_inv              1753 non-null   float64
 6   term                         1753 non-null   object
 7   int_rate                     1753 non-null   float64
 8   installment                  1753 non-null   float64
 9   grade                        1753 non-null   object
 10  sub_grade                    1753 non-null   object
 11  emp_title                    1654 non-null   object
 12  emp_length                   1707 non-null   object
 13  home_ownership               1753 non-null   object
 14  annual_inc                   1753 non-null   float64
 15  verification_status          1753 non-null   object
 16  issue_d                      1753 non-null   object
 17  loan_status                  1753 non-null   object
 18  pymnt_plan                   1753 non-null   object
 19  url                          1753 non-null   object
 20  desc                         992 non-null    object
 21  purpose                      1753 non-null   object
 22  title                        1753 non-null   object
 23  zip_code                     1753 non-null   object
 24  addr_state                   1753 non-null   object
 25  dti                          1753 non-null   float64
 26  delinq_2yrs                  1753 non-null   float64
 27  earliest_cr_line             1753 non-null   object
 28  inq_last_6mths               1753 non-null   float64
 29  mths_since_last_delinq       452 non-null    float64
 30  mths_since_last_record       38 non-null     float64
 31  open_acc                     1753 non-null   float64
 32  pub_rec                      1753 non-null   float64
 33  revol_bal                    1753 non-null   int64
 34  revol_util                   1753 non-null   float64
 35  total_acc                    1753 non-null   float64
 36  initial_list_status          1753 non-null   object
 37  out_prncp                    1753 non-null   float64
 38  out_prncp_inv                1753 non-null   float64
 39  total_pymnt                  1753 non-null   float64
 40  total_pymnt_inv              1753 non-null   float64
 41  total_rec_prncp              1752 non-null   float64
 42  total_rec_int                1752 non-null   float64
 43  total_rec_late_fee           1752 non-null   float64
 44  recoveries                   1752 non-null   float64
 45  collection_recovery_fee      1752 non-null   float64
 46  last_pymnt_d                 1751 non-null   object
 47  last_pymnt_amnt              1752 non-null   float64
 48  next_pymnt_d                 180 non-null    object
 49  last_credit_pull_d           1752 non-null   object
 50  collections_12_mths_ex_med   1752 non-null   float64
 51  mths_since_last_major_derog  0 non-null      float64
 52  policy_code                  1752 non-null   float64
 53  application_type             1752 non-null   object
 54  annual_inc_joint             0 non-null      float64
 55  dti_joint                    0 non-null      float64
 56  verification_status_joint    0 non-null      float64
 57  acc_now_delinq               1752 non-null   float64
 58  tot_coll_amt                 0 non-null      float64
 59  tot_cur_bal                  0 non-null      float64
 60  open_acc_6m                  0 non-null      float64
 61  open_il_6m                   0 non-null      float64
 62  open_il_12m                  0 non-null      float64
 63  open_il_24m                  0 non-null      float64
 64  mths_since_rcnt_il           0 non-null      float64
 65  total_bal_il                 0 non-null      float64
 66  il_util                      0 non-null      float64
 67  open_rv_12m                  0 non-null      float64
 68  open_rv_24m                  0 non-null      float64
 69  max_bal_bc                   0 non-null      float64
 70  all_util                     0 non-null      float64
 71  total_rev_hi_lim             0 non-null      float64
 72  inq_fi                       0 non-null      float64
 73  total_cu_tl                  0 non-null      float64
 74  inq_last_12m                 0 non-null      float64
dtypes: float64(47), int64(6), object(22)
memory usage: 1.0+ MB

In [ ]:
loan_data['emp_length'].unique()

array(['10+ years', '< 1 year', '1 year', '3 years', '8 years', '9 years',
       '4 years', '5 years', '6 years', '2 years', '7 years', nan],
      dtype=object)

In [ ]:
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('\+ years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('n/a', str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '')

<ipython-input-38-f42231df6a9a>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  loan_data['emp_length_int'] = loan_data['emp_length'].str.replace('\+ years', '')

In [ ]:
type(loan_data['emp_length_int'][0])

str

In [ ]:
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'])

In [ ]:
type(loan_data['emp_length_int'][0])

numpy.float64

In [ ]:
loan_data['earliest_cr_line']
## string variables but were actually supposed to be date variables
## all values here are string

0       Jan-85
1       Apr-99
2       Nov-01
3       Feb-96
4       Jan-96
         ...
1748    Nov-99
1749    Feb-90
1750    Jul-06
1751    Mar-04
1752    Jul-93
Name: earliest_cr_line, Length: 1753, dtype: object

In [ ]:
loan_data['earliest_cr_line_date'] = pd.to_datetime(loan_data['earliest_cr_line'], format = '%b-%y')

In [ ]:
type(loan_data['earliest_cr_line_date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [ ]:
pd.to_datetime('2017-12-01') - loan_data['earliest_cr_line_date']

0      12022 days
1       6819 days
2       5874 days
3       7974 days
4       8005 days
          ...
1748    6605 days
1749   10165 days
1750    4171 days
1751    5023 days
1752    8919 days
Name: earliest_cr_line_date, Length: 1753, dtype: timedelta64[ns]

In [ ]:
loan_data['mths_since_earliest_cr_line'] = round(pd.to_numeric((pd.to_datetime('2017-12-01') - loan_data['earliest_cr_line_date'])/np.timedelta64(1, 'M')))

In [ ]:
loan_data['mths_since_earliest_cr_line'].describe()

count    1753.000000
mean      229.660011
std        77.360396
min      -537.000000
25%       179.000000
50%       214.000000
75%       265.000000
max       585.000000
Name: mths_since_earliest_cr_line, dtype: float64

In [ ]:
loan_data.loc[: , ['earliest_cr_line']]

     earliest_cr_line
0              Jan-85
1              Apr-99
2              Nov-01
3              Feb-96
4              Jan-96
...               ...
1748           Nov-99
1749           Feb-90
1750           Jul-06
1751           Mar-04
1752           Jul-93

[1753 rows x 1 columns]

In [ ]:
loan_data.loc[: , ['earliest_cr_line', 'earliest_cr_line_date', 'mths_since_earliest_cr_line']][loan_data['mths_since_earliest_cr_line']<0]

     earliest_cr_line earliest_cr_line_date  mths_since_earliest_cr_line
1580           Sep-62            2062-09-01                       -537.0

In [ ]:
loan_data['mths_since_earliest_cr_line'][loan_data['mths_since_earliest_cr_line']< 0] = loan_data['mths_since_earliest_cr_line'].max()

<ipython-input-50-33e169d13e7b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  loan_data['mths_since_earliest_cr_line'][loan_data['mths_since_earliest_cr_line']< 0] = loan_data['mths_since_earliest_cr_line'].max()

In [ ]:
min(loan_data['mths_since_earliest_cr_line'])

109.0

Preprocessing few discrete varaibles

In [ ]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1753 entries, 0 to 1752
Data columns (total 78 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   1753 non-null   int64
 1   id                           1753 non-null   int64
 2   member_id                    1753 non-null   int64
 3   loan_amnt                    1753 non-null   int64
 4   funded_amnt                  1753 non-null   int64
 5   funded_amnt_inv              1753 non-null   float64
 6   term                         1753 non-null   object
 7   int_rate                     1753 non-null   float64
 8   installment                  1753 non-null   float64
 9   grade                        1753 non-null   object
 10  sub_grade                    1753 non-null   object
 11  emp_title                    1654 non-null   object
 12  emp_length                   1707 non-null   object
 13  home_ownership               1753 non-null   object
 14  annual_inc                   1753 non-null   float64
 15  verification_status          1753 non-null   object
 16  issue_d                      1753 non-null   object
 17  loan_status                  1753 non-null   object
 18  pymnt_plan                   1753 non-null   object
 19  url                          1753 non-null   object
 20  desc                         992 non-null    object
 21  purpose                      1753 non-null   object
 22  title                        1753 non-null   object
 23  zip_code                     1753 non-null   object
 24  addr_state                   1753 non-null   object
 25  dti                          1753 non-null   float64
 26  delinq_2yrs                  1753 non-null   float64
 27  earliest_cr_line             1753 non-null   object
 28  inq_last_6mths               1753 non-null   float64
 29  mths_since_last_delinq       452 non-null    float64
 30  mths_since_last_record       38 non-null     float64
 31  open_acc                     1753 non-null   float64
 32  pub_rec                      1753 non-null   float64
 33  revol_bal                    1753 non-null   int64
 34  revol_util                   1753 non-null   float64
 35  total_acc                    1753 non-null   float64
 36  initial_list_status          1753 non-null   object
 37  out_prncp                    1753 non-null   float64
 38  out_prncp_inv                1753 non-null   float64
 39  total_pymnt                  1753 non-null   float64
 40  total_pymnt_inv              1753 non-null   float64
 41  total_rec_prncp              1752 non-null   float64
 42  total_rec_int                1752 non-null   float64
 43  total_rec_late_fee           1752 non-null   float64
 44  recoveries                   1752 non-null   float64
 45  collection_recovery_fee      1752 non-null   float64
 46  last_pymnt_d                 1751 non-null   object
 47  last_pymnt_amnt              1752 non-null   float64
 48  next_pymnt_d                 180 non-null    object
 49  last_credit_pull_d           1752 non-null   object
 50  collections_12_mths_ex_med   1752 non-null   float64
 51  mths_since_last_major_derog  0 non-null      float64
 52  policy_code                  1752 non-null   float64
 53  application_type             1752 non-null   object
 54  annual_inc_joint             0 non-null      float64
 55  dti_joint                    0 non-null      float64
 56  verification_status_joint    0 non-null      float64
 57  acc_now_delinq               1752 non-null   float64
 58  tot_coll_amt                 0 non-null      float64
 59  tot_cur_bal                  0 non-null      float64
 60  open_acc_6m                  0 non-null      float64
 61  open_il_6m                   0 non-null      float64
 62  open_il_12m                  0 non-null      float64
 63  open_il_24m                  0 non-null      float64
 64  mths_since_rcnt_il           0 non-null      float64
 65  total_bal_il                 0 non-null      float64
 66  il_util                      0 non-null      float64
 67  open_rv_12m                  0 non-null      float64
 68  open_rv_24m                  0 non-null      float64
 69  max_bal_bc                   0 non-null      float64
 70  all_util                     0 non-null      float64
 71  total_rev_hi_lim             0 non-null      float64
 72  inq_fi                       0 non-null      float64
 73  total_cu_tl                  0 non-null      float64
 74  inq_last_12m                 0 non-null      float64
 75  emp_length_int               1707 non-null   float64
 76  earliest_cr_line_date        1753 non-null   datetime64[ns]
 77  mths_since_earliest_cr_line  1753 non-null   float64
dtypes: datetime64[ns](1), float64(49), int64(6), object(22)
memory usage: 1.0+ MB

In [ ]:
## pandas have a built in function to create dummy variables

pd.get_dummies(loan_data['grade'])

      A  B  C  D  E  F  G
0     0  1  0  0  0  0  0
1     0  0  1  0  0  0  0
2     0  0  1  0  0  0  0
3     0  0  1  0  0  0  0
4     0  1  0  0  0  0  0
...  .. .. .. .. .. .. ..
1748  0  0  0  0  0  1  0
1749  0  1  0  0  0  0  0
1750  0  0  1  0  0  0  0
1751  0  1  0  0  0  0  0
1752  0  0  1  0  0  0  0

[1753 rows x 7 columns]

In [ ]:
pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ':')

      grade:A  grade:B  grade:C  grade:D  grade:E  grade:F  grade:G
0           0        1        0        0        0        0        0
1           0        0        1        0        0        0        0
2           0        0        1        0        0        0        0
3           0        0        1        0        0        0        0
4           0        1        0        0        0        0        0
...       ...      ...      ...      ...      ...      ...      ...
1748        0        0        0        0        0        1        0
1749        0        1        0        0        0        0        0
1750        0        0        1        0        0        0        0
1751        0        1        0        0        0        0        0
1752        0        0        1        0        0        0        0

[1753 rows x 7 columns]

In [ ]:
loan_data_dummies = [pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['sub_grade'], prefix = 'sub_grade', prefix_sep = ':'),
                     pd.get_dummies(loan_data['home_ownership'], prefix = 'home_ownership', prefix_sep = ':'),
                     pd.get_dummies(loan_data['verification_status'], prefix = 'verification_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['loan_status'], prefix = 'loan_status', prefix_sep = ':'),
                     pd.get_dummies(loan_data['purpose'], prefix = 'purpose', prefix_sep = ':'),
                     pd.get_dummies(loan_data['addr_state'], prefix = 'addr_state', prefix_sep = ':'),
                     pd.get_dummies(loan_data['initial_list_status'], prefix = 'initial_list_status', prefix_sep = ':')]

In [ ]:
loan_data_dummies = pd.concat(loan_data_dummies, axis = 1)

In [ ]:
type(loan_data_dummies)

pandas.core.frame.DataFrame

In [ ]:
loan_data = pd.concat([loan_data, loan_data_dummies], axis = 1)
##concatanating by columns

In [ ]:
loan_data.columns.values

array(['Unnamed: 0', 'id', 'member_id', 'loan_amnt', 'funded_amnt',
       'funded_amnt_inv', 'term', 'int_rate', 'installment', 'grade',
       'sub_grade', 'emp_title', 'emp_length', 'home_ownership',
       'annual_inc', 'verification_status', 'issue_d', 'loan_status',
       'pymnt_plan', 'url', 'desc', 'purpose', 'title', 'zip_code',
       'addr_state', 'dti', 'delinq_2yrs', 'earliest_cr_line',
       'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int', 'total_rec_late_fee',
       'recoveries', 'collection_recovery_fee', 'last_pymnt_d',
       'last_pymnt_amnt', 'next_pymnt_d', 'last_credit_pull_d',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'application_type', 'annual_inc_joint', 'dti_joint',
       'verification_status_joint', 'acc_now_delinq', 'tot_coll_amt',
       'tot_cur_bal', 'open_acc_6m', 'open_il_6m', 'open_il_12m',
       'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il', 'il_util',
       'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'emp_length_int', 'earliest_cr_line_date',
       'mths_since_earliest_cr_line', 'grade:A', 'grade:B', 'grade:C',
       'grade:D', 'grade:E', 'grade:F', 'grade:G', 'sub_grade:A1',
       'sub_grade:A2', 'sub_grade:A3', 'sub_grade:A4', 'sub_grade:A5',
       'sub_grade:B1', 'sub_grade:B2', 'sub_grade:B3', 'sub_grade:B4',
       'sub_grade:B5', 'sub_grade:C1', 'sub_grade:C2', 'sub_grade:C3',
       'sub_grade:C4', 'sub_grade:C5', 'sub_grade:D1', 'sub_grade:D2',
       'sub_grade:D3', 'sub_grade:D4', 'sub_grade:D5', 'sub_grade:E1',
       'sub_grade:E2', 'sub_grade:E3', 'sub_grade:E4', 'sub_grade:E5',
       'sub_grade:F1', 'sub_grade:F2', 'sub_grade:F3', 'sub_grade:F4',
       'sub_grade:F5', 'sub_grade:G1', 'sub_grade:G2', 'sub_grade:G3',
       'sub_grade:G4', 'sub_grade:G5', 'home_ownership:MORTGAGE',
       'home_ownership:OWN', 'home_ownership:RENT',
       'verification_status:Not Verified',
       'verification_status:Source Verified',
       'verification_status:Verified', 'loan_status:Charged Off',
       'loan_status:Current', 'loan_status:Default',
       'loan_status:Fully Paid', 'loan_status:In Grace Period',
       'loan_status:Late (31-120 days)', 'purpose:car',
       'purpose:credit_card', 'purpose:debt_consolidation',
       'purpose:home_improvement', 'purpose:house',
       'purpose:major_purchase', 'purpose:medical', 'purpose:moving',
       'purpose:other', 'purpose:renewable_energy',
       'purpose:small_business', 'purpose:vacation', 'purpose:wedding',
       'addr_state:AK', 'addr_state:AL', 'addr_state:AR', 'addr_state:AZ',
       'addr_state:CA', 'addr_state:CO', 'addr_state:CT', 'addr_state:DC',
       'addr_state:DE', 'addr_state:FL', 'addr_state:GA', 'addr_state:HI',
       'addr_state:IL', 'addr_state:KS', 'addr_state:KY', 'addr_state:LA',
       'addr_state:MA', 'addr_state:MD', 'addr_state:MI', 'addr_state:MN',
       'addr_state:MO', 'addr_state:MT', 'addr_state:NC', 'addr_state:NH',
       'addr_state:NJ', 'addr_state:NM', 'addr_state:NV', 'addr_state:NY',
       'addr_state:OH', 'addr_state:OK', 'addr_state:OR', 'addr_state:PA',
       'addr_state:RI', 'addr_state:SC', 'addr_state:SD', 'addr_state:TX',
       'addr_state:UT', 'addr_state:VA', 'addr_state:VT', 'addr_state:WA',
       'addr_state:WI', 'addr_state:WV', 'addr_state:WY',
       'initial_list_status:f'], dtype=object)

Check for missing values and clean

In [ ]:
loan_data.isnull()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,emp_length_int,earliest_cr_line_date,mths_since_earliest_cr_line,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,grade:G,sub_grade:A1,sub_grade:A2,sub_grade:A3,sub_grade:A4,sub_grade:A5,sub_grade:B1,sub_grade:B2,sub_grade:B3,sub_grade:B4,sub_grade:B5,sub_grade:C1,sub_grade:C2,sub_grade:C3,sub_grade:C4,sub_grade:C5,sub_grade:D1,sub_grade:D2,sub_grade:D3,sub_grade:D4,sub_grade:D5,sub_grade:E1,sub_grade:E2,sub_grade:E3,sub_grade:E4,sub_grade:E5,sub_grade:F1,sub_grade:F2,sub_grade:F3,sub_grade:F4,sub_grade:F5,sub_grade:G1,sub_grade:G2,sub_grade:G3,sub_grade:G4,sub_grade:G5,home_ownership:MORTGAGE,home_ownership:OWN,home_ownership:RENT,verification_status:Not Verified,verification_status:Source Verified,verification_status:Verified,loan_status:Charged Off,loan_status:Current,loan_status:Default,loan_status:Fully Paid,loan_status:In Grace Period,loan_status:Late (31-120 days),purpose:car,purpose:credit_card,purpose:debt_consolidation,purpose:home_improvement,purpose:house,purpose:major_purchase,purpose:medical,purpose:moving,purpose:other,purpose:renewable_energy,purpose:small_business,purpose:vacation,purpose:wedding,addr_state:AK,addr_state:AL,addr_state:AR,addr_state:AZ,addr_state:CA,addr_state:CO,addr_state:CT,addr_state:DC,addr_state:DE,addr_state:FL,addr_state:GA,addr_state:HI,addr_state:IL,addr_state:KS,addr_state:KY,addr_state:LA,addr_state:MA,addr_state:MD,addr_state:MI,addr_state:MN,addr_state:MO,addr_state:MT,addr_state:NC,addr_state:NH,addr_state:NJ,addr_state:NM,addr_state:NV,addr_state:NY,addr_state:OH,addr_state:OK,addr_state:OR,addr_state:PA,addr_state:RI,addr_state:SC,addr_state:SD,addr_state:TX,addr_state:UT,addr_state:VA,addr_state:VT,addr_state:WA,addr_state:WI,addr_state:WV,addr_state:WY,initial_list_status:f
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1748,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1749,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1750,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1751,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,True,True,True,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1752,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
pd.options.display.max_rows = None
loan_data.isnull().sum()

Unnamed: 0                                0
id                                        0
member_id                                 0
loan_amnt                                 0
funded_amnt                               0
funded_amnt_inv                           0
term                                      0
int_rate                                  0
installment                               0
grade                                     0
sub_grade                                 0
emp_title                                99
emp_length                               46
home_ownership                            0
annual_inc                                0
verification_status                       0
issue_d                                   0
loan_status                               0
pymnt_plan                                0
url                                       0
desc                                    761
purpose                                   0
title                                     0
zip_code                                  0
addr_state                                0
dti                                       0
delinq_2yrs                               0
earliest_cr_line                          0
inq_last_6mths                            0
mths_since_last_delinq                 1301
mths_since_last_record                 1715
open_acc                                  0
pub_rec                                   0
revol_bal                                 0
revol_util                                0
total_acc                                 0
initial_list_status                       0
out_prncp                                 0
out_prncp_inv                             0
total_pymnt                               0
total_pymnt_inv                           0
total_rec_prncp                           1
total_rec_int                             1
total_rec_late_fee                        1
recoveries                                1
collection_recovery_fee                   1
last_pymnt_d                              2
last_pymnt_amnt                           1
next_pymnt_d                           1573
last_credit_pull_d                        1
collections_12_mths_ex_med                1
mths_since_last_major_derog            1753
policy_code                               1
application_type                          1
annual_inc_joint                       1753
dti_joint                              1753
verification_status_joint              1753
acc_now_delinq                            1
tot_coll_amt                           1753
tot_cur_bal                            1753
open_acc_6m                            1753
open_il_6m                             1753
open_il_12m                            1753
open_il_24m                            1753
mths_since_rcnt_il                     1753
total_bal_il                           1753
il_util                                1753
open_rv_12m                            1753
open_rv_24m                            1753
max_bal_bc                             1753
all_util                               1753
total_rev_hi_lim                       1753
inq_fi                                 1753
total_cu_tl                            1753
inq_last_12m                           1753
emp_length_int                           46
earliest_cr_line_date                     0
mths_since_earliest_cr_line               0
grade:A                                   0
grade:B                                   0
grade:C                                   0
grade:D                                   0
grade:E                                   0
grade:F                                   0
grade:G                                   0
sub_grade:A1                              0
sub_grade:A2                              0
sub_grade:A3                              0
sub_grade:A4                              0
sub_grade:A5                              0
sub_grade:B1                              0
sub_grade:B2                              0
sub_grade:B3                              0
sub_grade:B4                              0
sub_grade:B5                              0
sub_grade:C1                              0
sub_grade:C2                              0
sub_grade:C3                              0
sub_grade:C4                              0
sub_grade:C5                              0
sub_grade:D1                              0
sub_grade:D2                              0
sub_grade:D3                              0
sub_grade:D4                              0
sub_grade:D5                              0
sub_grade:E1                              0
sub_grade:E2                              0
sub_grade:E3                              0
sub_grade:E4                              0
sub_grade:E5                              0
sub_grade:F1                              0
sub_grade:F2                              0
sub_grade:F3                              0
sub_grade:F4                              0
sub_grade:F5                              0
sub_grade:G1                              0
sub_grade:G2                              0
sub_grade:G3                              0
sub_grade:G4                              0
sub_grade:G5                              0
home_ownership:MORTGAGE                   0
home_ownership:OWN                        0
home_ownership:RENT                       0
verification_status:Not Verified          0
verification_status:Source Verified       0
verification_status:Verified              0
loan_status:Charged Off                   0
loan_status:Current                       0
loan_status:Default                       0
loan_status:Fully Paid                    0
loan_status:In Grace Period               0
loan_status:Late (31-120 days)            0
purpose:car                               0
purpose:credit_card                       0
purpose:debt_consolidation                0
purpose:home_improvement                  0
purpose:house                             0
purpose:major_purchase                    0
purpose:medical                           0
purpose:moving                            0
purpose:other                             0
purpose:renewable_energy                  0
purpose:small_business                    0
purpose:vacation                          0
purpose:wedding                           0
addr_state:AK                             0
addr_state:AL                             0
addr_state:AR                             0
addr_state:AZ                             0
addr_state:CA                             0
addr_state:CO                             0
addr_state:CT                             0
addr_state:DC                             0
addr_state:DE                             0
addr_state:FL                             0
addr_state:GA                             0
addr_state:HI                             0
addr_state:IL                             0
addr_state:KS                             0
addr_state:KY                             0
addr_state:LA                             0
addr_state:MA                             0
addr_state:MD                             0
addr_state:MI                             0
addr_state:MN                             0
addr_state:MO                             0
addr_state:MT                             0
addr_state:NC                             0
addr_state:NH                             0
addr_state:NJ                             0
addr_state:NM                             0
addr_state:NV                             0
addr_state:NY                             0
addr_state:OH                             0
addr_state:OK                             0
addr_state:OR                             0
addr_state:PA                             0
addr_state:RI                             0
addr_state:SC                             0
addr_state:SD                             0
addr_state:TX                             0
addr_state:UT                             0
addr_state:VA                             0
addr_state:VT                             0
addr_state:WA                             0
addr_state:WI                             0
addr_state:WV                             0
addr_state:WY                             0
initial_list_status:f                     0
dtype: int64

In [ ]:
pd.options.display.max_rows = 100

In [ ]:
loan_data['total_rev_hi_lim'].fillna(loan_data['funded_amnt'], inplace = True)

In [ ]:
loan_data['total_rev_hi_lim'].isnull().sum()

0

In [ ]:
loan_data['loan_status'].unique()

array(['Fully Paid', 'Charged Off', 'Current', 'Default',
       'Late (31-120 days)', 'In Grace Period'], dtype=object)

In [ ]:
loan_data['loan_status'].value_counts() / loan_data['loan_status'].count()

Fully Paid            0.718197
Charged Off           0.179122
Current               0.099258
Late (31-120 days)    0.001711
In Grace Period       0.001141
Default               0.000570
Name: loan_status, dtype: float64

In [ ]:
loan_data['good_bad'] = np.where(loan_data['loan_status'].isin(['Charged Off', 'Default', 'Does not meet the credit policy. Status:Charged Off', 'Late (31-120 days)']), 0, 1)

In [ ]:
loan_data['good_bad']

0       1
1       0
2       1
3       1
4       1
       ..
1748    0
1749    0
1750    1
1751    0
1752    0
Name: good_bad, Length: 1753, dtype: int64

Splitting the data into training and testing data set

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'])

[      Unnamed: 0       id  member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
 467          467  1062818    1294695      20000        20000      19523.42192
 438          438  1063528    1296094      21000        21000      20975.00000
 544          544  1062860    1295340      10000        10000      10000.00000
 45            45  1051117    1282787      14000        14000      14000.00000
 493          493  1063407    1295960      14050        14050      14050.00000
 ...          ...      ...        ...        ...          ...              ...
 1731        1731  1047018    1277883       5000         5000       5000.00000
 676          676  1061204    1293007      10375        10375      10375.00000
 1071        1071  1056772    1288324      12000        12000      12000.00000
 1332        1332  1052469    1284000      20000        20000      20000.00000
 1057        1057  1056856    1288410      20000        20000      19975.00000

             term  int_rate  installment grade sub_grade  \
 467    60 months     18.64       514.86     E        E1
 438    36 months     12.69       704.45     B        B5
 544    36 months     16.29       353.01     D        D1
 45     36 months      9.91       451.15     B        B1
 493    36 months      8.90       446.14     A        A5
 ...          ...       ...          ...   ...       ...
 1731   36 months     11.71       165.38     B        B3
 676    36 months     14.27       355.96     C        C2
 1071   36 months     12.69       402.54     B        B5
 1332   36 months     17.27       715.75     D        D3
 1057   60 months     18.25       510.60     D        D5

                             emp_title emp_length home_ownership  annual_inc  \
 467                cardinal logistics    3 years       MORTGAGE     80000.0
 438                     Merrill Lynch    8 years       MORTGAGE    135000.0
 544                              volt    3 years           RENT     83200.0
 45                  golfers warehouse    6 years           RENT     80000.0
 493             Everest Entertainment    3 years       MORTGAGE    120000.0
 ...                               ...        ...            ...         ...
 1731                   Wolverine Tube  10+ years           RENT     43000.0
 676                   YH America Inc.    5 years           RENT     35000.0
 1071                    Credit Suisse  10+ years           RENT    200000.0
 1332  California Heating & Sheetmetal  10+ years       MORTGAGE     50000.0
 1057       memorial healthcare system    9 years           RENT    105000.0

      verification_status issue_d  loan_status pymnt_plan  \
 467      Source Verified  Dec-11   Fully Paid          n
 438             Verified  Dec-11   Fully Paid          n
 544      Source Verified  Dec-11   Fully Paid          n
 45          Not Verified  Dec-11   Fully Paid          n
 493             Verified  Dec-11   Fully Paid          n
 ...                  ...     ...          ...        ...
 1731     Source Verified  Dec-11   Fully Paid          n
 676         Not Verified  Dec-11   Fully Paid          n
 1071     Source Verified  Dec-11   Fully Paid          n
 1332     Source Verified  Dec-11  Charged Off          n
 1057            Verified  Dec-11   Fully Paid          n

                                                     url  \
 467   https://www.lendingclub.com/browse/loanDetail....
 438   https://www.lendingclub.com/browse/loanDetail....
 544   https://www.lendingclub.com/browse/loanDetail....
 45    https://www.lendingclub.com/browse/loanDetail....
 493   https://www.lendingclub.com/browse/loanDetail....
 ...                                                 ...
 1731  https://www.lendingclub.com/browse/loanDetail....
 676   https://www.lendingclub.com/browse/loanDetail....
 1071  https://www.lendingclub.com/browse/loanDetail....
 1332  https://www.lendingclub.com/browse/loanDetail....
 1057  https://www.lendingclub.com/browse/loanDetail....

                                                    desc             purpose  \
 467     Borrower added on 12/09/11 > debt consolidat...  debt_consolidation
 438                                                 NaN  debt_consolidation
 544     Borrower added on 12/08/11 > refianance cred...         credit_card
 45      Borrower added on 12/15/11 > i am opening a ...      small_business
 493     Borrower added on 12/09/11 >  There are thre...      major_purchase
 ...                                                 ...                 ...
 1731                                                NaN               other
 676                                                 NaN         credit_card
 1071                                                NaN  debt_consolidation
 1332                                                NaN  debt_consolidation
 1057                                                NaN  debt_consolidation

                                  title zip_code addr_state    dti  \
 467                            my plan    850xx         AZ  23.47
 438                    Short Term Loan    430xx         OH   8.52
 544                               refi    982xx         WA  17.03
 45                 Small Business Loan    010xx         MA  10.00
 493   Loan Payoff and Home Improvement    112xx         NY   2.21
 ...                                ...      ...        ...    ...
 1731                     Personal Loan    748xx         OK  13.48
 676          Credit Card Consolidation    403xx         KY  22.39
 1071           Debt Consolidation Loan    105xx         NY   6.61
 1332           Debt Consolidation Loan    955xx         CA   3.02
 1057            debt consolidation now    333xx         FL  12.74

       delinq_2yrs earliest_cr_line  inq_last_6mths  mths_since_last_delinq  \
 467           0.0           Jan-01             0.0                     NaN
 438           0.0           Feb-00             1.0                    81.0
 544           0.0           Jul-05             1.0                     NaN
 45            0.0           Jul-99             1.0                    45.0
 493           0.0           May-06             2.0                     NaN
 ...           ...              ...             ...                     ...
 1731          0.0           Sep-95             0.0                    30.0
 676           0.0           Oct-03             1.0                     NaN
 1071          0.0           Jun-95             2.0                    82.0
 1332          2.0           Sep-93             0.0                    17.0
 1057          0.0           Sep-01             1.0                     NaN

       mths_since_last_record  open_acc  pub_rec  revol_bal  revol_util  \
 467                      NaN       8.0      0.0      11952        88.5
 438                      NaN      11.0      0.0      30361        63.0
 544                      NaN       8.0      0.0      12603        92.0
 45                       NaN       7.0      0.0       2219        13.4
 493                      NaN       9.0      0.0       2217        18.8
 ...                      ...       ...      ...        ...         ...
 1731                     NaN       3.0      0.0       3007        50.1
 676                      NaN       7.0      0.0      10084        65.9
 1071                     NaN       7.0      0.0      16375        71.5
 1332                     NaN       3.0      0.0       4245        38.2
 1057                     NaN       8.0      0.0      14106        90.4

       total_acc initial_list_status  out_prncp  out_prncp_inv   total_pymnt  \
 467        13.0                   f        0.0            0.0  22955.760000
 438        24.0                   f        0.0            0.0  24283.820000
 544        15.0                   f        0.0            0.0  11713.050000
 45         40.0                   f        0.0            0.0  16239.914130
 493        13.0                   f        0.0            0.0  15808.020000
 ...         ...                 ...        ...            ...           ...
 1731       28.0                   f        0.0            0.0   5950.733572
 676        15.0                   f        0.0            0.0  12810.166700
 1071       21.0                   f        0.0            0.0  13496.990000
 1332       11.0                   f        0.0            0.0  26149.350000
 1057       18.0                   f        0.0            0.0  23684.560000

       total_pymnt_inv  total_rec_prncp  total_rec_int  total_rec_late_fee  \
 467          21817.92         20000.00        2955.76            0.000000
 438          24254.93         21000.01        3283.81            0.000000
 544          11713.05         10000.00        1713.05            0.000000
 45           16239.91         14000.00        2239.91            0.000000
 493          15808.02         14050.00        1758.02            0.000000
 ...               ...              ...            ...                 ...
 1731          5950.73          5000.00         950.73            0.000000
 676          12810.17         10375.00        2435.17            0.000000
 1071         13496.99         12000.00        1496.99            0.000000
 1332         26149.35         19675.80        6146.68           14.978219
 1057         23655.00         20000.00        3684.56            0.000000

       recoveries  collection_recovery_fee last_pymnt_d  last_pymnt_amnt  \
 467         0.00                   0.0000       Oct-12         18326.72
 438         0.00                   0.0000       Jul-13         11650.08
 544         0.00                   0.0000       May-13            54.68
 45          0.00                   0.0000       Jan-15           457.91
 493         0.00                   0.0000       Dec-13          5569.67
 ...          ...                      ...          ...              ...
 1731        0.00                   0.0000       Dec-14           176.99
 676         0.00                   0.0000       Dec-14           368.99
 1071        0.00                   0.0000       Feb-13          8277.69
 1332      311.89                  56.1402       Jul-15           715.75
 1057        0.00                   0.0000       Jan-13         17577.92

      next_pymnt_d last_credit_pull_d  collections_12_mths_ex_med  \
 467           NaN             Nov-12                         0.0
 438           NaN             Oct-15                         0.0
 544           NaN             Jan-16                         0.0
 45            NaN             Jan-16                         0.0
 493           NaN             Dec-13                         0.0
 ...           ...                ...                         ...
 1731          NaN             Jan-16                         0.0
 676           NaN             Dec-14                         0.0
 1071          NaN             Oct-13                         0.0
 1332          NaN             Jan-16                         0.0
 1057          NaN             Nov-14                         0.0

       mths_since_last_major_derog  policy_code application_type  \
 467                           NaN          1.0       INDIVIDUAL
 438                           NaN          1.0       INDIVIDUAL
 544                           NaN          1.0       INDIVIDUAL
 45                            NaN          1.0       INDIVIDUAL
 493                           NaN          1.0       INDIVIDUAL
 ...                           ...          ...              ...
 1731                          NaN          1.0       INDIVIDUAL
 676                           NaN          1.0       INDIVIDUAL
 1071                          NaN          1.0       INDIVIDUAL
 1332                          NaN          1.0       INDIVIDUAL
 1057                          NaN          1.0       INDIVIDUAL

       annual_inc_joint  dti_joint  verification_status_joint  acc_now_delinq  \
 467                NaN        NaN                        NaN             0.0
 438                NaN        NaN                        NaN             0.0
 544                NaN        NaN                        NaN             0.0
 45                 NaN        NaN                        NaN             0.0
 493                NaN        NaN                        NaN             0.0
 ...                ...        ...                        ...             ...
 1731               NaN        NaN                        NaN             0.0
 676                NaN        NaN                        NaN             0.0
 1071               NaN        NaN                        NaN             0.0
 1332               NaN        NaN                        NaN             0.0
 1057               NaN        NaN                        NaN             0.0

       tot_coll_amt  tot_cur_bal  open_acc_6m  open_il_6m  open_il_12m  \
 467            NaN          NaN          NaN         NaN          NaN
 438            NaN          NaN          NaN         NaN          NaN
 544            NaN          NaN          NaN         NaN          NaN
 45             NaN          NaN          NaN         NaN          NaN
 493            NaN          NaN          NaN         NaN          NaN
 ...            ...          ...          ...         ...          ...
 1731           NaN          NaN          NaN         NaN          NaN
 676            NaN          NaN          NaN         NaN          NaN
 1071           NaN          NaN          NaN         NaN          NaN
 1332           NaN          NaN          NaN         NaN          NaN
 1057           NaN          NaN          NaN         NaN          NaN

       open_il_24m  mths_since_rcnt_il  total_bal_il  il_util  open_rv_12m  \
 467           NaN                 NaN           NaN      NaN          NaN
 438           NaN                 NaN           NaN      NaN          NaN
 544           NaN                 NaN           NaN      NaN          NaN
 45            NaN                 NaN           NaN      NaN          NaN
 493           NaN                 NaN           NaN      NaN          NaN
 ...           ...                 ...           ...      ...          ...
 1731          NaN                 NaN           NaN      NaN          NaN
 676           NaN                 NaN           NaN      NaN          NaN
 1071          NaN                 NaN           NaN      NaN          NaN
 1332          NaN                 NaN           NaN      NaN          NaN
 1057          NaN                 NaN           NaN      NaN          NaN

       open_rv_24m  max_bal_bc  all_util  total_rev_hi_lim  inq_fi  \
 467           NaN         NaN       NaN           20000.0     NaN
 438           NaN         NaN       NaN           21000.0     NaN
 544           NaN         NaN       NaN           10000.0     NaN
 45            NaN         NaN       NaN           14000.0     NaN
 493           NaN         NaN       NaN           14050.0     NaN
 ...           ...         ...       ...               ...     ...
 1731          NaN         NaN       NaN            5000.0     NaN
 676           NaN         NaN       NaN           10375.0     NaN
 1071          NaN         NaN       NaN           12000.0     NaN
 1332          NaN         NaN       NaN           20000.0     NaN
 1057          NaN         NaN       NaN           20000.0     NaN

       total_cu_tl  inq_last_12m  emp_length_int earliest_cr_line_date  \
 467           NaN           NaN             3.0            2001-01-01
 438           NaN           NaN             8.0            2000-02-01
 544           NaN           NaN             3.0            2005-07-01
 45            NaN           NaN             6.0            1999-07-01
 493           NaN           NaN             3.0            2006-05-01
 ...           ...           ...             ...                   ...
 1731          NaN           NaN            10.0            1995-09-01
 676           NaN           NaN             5.0            2003-10-01
 1071          NaN           NaN            10.0            1995-06-01
 1332          NaN           NaN            10.0            1993-09-01
 1057          NaN           NaN             9.0            2001-09-01

       mths_since_earliest_cr_line  grade:A  grade:B  grade:C  grade:D  \
 467                         203.0        0        0        0        0
 438                         214.0        0        1        0        0
 544                         149.0        0        0        0        1
 45                          221.0        0        1        0        0
 493                         139.0        1        0        0        0
 ...                           ...      ...      ...      ...      ...
 1731                        267.0        0        1        0        0
 676                         170.0        0        0        1        0
 1071                        270.0        0        1        0        0
 1332                        291.0        0        0        0        1
 1057                        195.0        0        0        0        1

       grade:E  grade:F  grade:G  sub_grade:A1  sub_grade:A2  sub_grade:A3  \
 467         1        0        0             0             0             0
 438         0        0        0             0             0             0
 544         0        0        0             0             0             0
 45          0        0        0             0             0             0
 493         0        0        0             0             0             0
 ...       ...      ...      ...           ...           ...           ...
 1731        0        0        0             0             0             0
 676         0        0        0             0             0             0
 1071        0        0        0             0             0             0
 1332        0        0        0             0             0             0
 1057        0        0        0             0             0             0

       sub_grade:A4  sub_grade:A5  sub_grade:B1  sub_grade:B2  sub_grade:B3  \
 467              0             0             0             0             0
 438              0             0             0             0             0
 544              0             0             0             0             0
 45               0             0             1             0             0
 493              0             1             0             0             0
 ...            ...           ...           ...           ...           ...
 1731             0             0             0             0             1
 676              0             0             0             0             0
 1071             0             0             0             0             0
 1332             0             0             0             0             0
 1057             0             0             0             0             0

       sub_grade:B4  sub_grade:B5  sub_grade:C1  sub_grade:C2  sub_grade:C3  \
 467              0             0             0             0             0
 438              0             1             0             0             0
 544              0             0             0             0             0
 45               0             0             0             0             0
 493              0             0             0             0             0
 ...            ...           ...           ...           ...           ...
 1731             0             0             0             0             0
 676              0             0             0             1             0
 1071             0             1             0             0             0
 1332             0             0             0             0             0
 1057             0             0             0             0             0

       sub_grade:C4  sub_grade:C5  sub_grade:D1  sub_grade:D2  sub_grade:D3  \
 467              0             0             0             0             0
 438              0             0             0             0             0

In [ ]:
loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'])

In [ ]:
loan_data_inputs_train.shape

(1314, 189)

In [ ]:
loan_data_targets_train.shape

(1314,)

In [ ]:
loan_data_inputs_test.shape

(439, 189)

In [ ]:
loan_data_targets_test.shape

(439,)

In [ ]:
loan_data_inputs_train, loan_data_inputs_test, loan_data_targets_train, loan_data_targets_test = train_test_split(loan_data.drop('good_bad', axis = 1), loan_data['good_bad'], test_size = 0.2, random_state = 42)

In [ ]:
loan_data_inputs_train.shape

(1402, 189)

In [ ]:
loan_data_targets_train.shape

(1402,)

In [ ]:
loan_data_inputs_test.shape

(351, 189)

In [ ]:
loan_data_targets_test.shape

(351,)

Data Preparation

In [ ]:
df_inputs_prepr = loan_data_inputs_train

In [ ]:
df_targets_prepr = loan_data_targets_train

In [ ]:
df_inputs_prepr['grade'].unique()

array(['C', 'B', 'A', 'D', 'E', 'F', 'G'], dtype=object)

In [ ]:
df1 = pd.concat([df_inputs_prepr['grade'], df_targets_prepr], axis = 1)
df1.head()

     grade  good_bad
199      C         1
1375     B         1
798      A         0
1233     D         1
1575     B         1

In [ ]:
df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].count()

  grade  good_bad
0     A       296
1     B       469
2     C       304
3     D       189
4     E       101
5     F        37
6     G         6

In [ ]:
df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].mean()

  grade  good_bad
0     A  0.885135
1     B  0.867804
2     C  0.812500
3     D  0.740741
4     E  0.732673
5     F  0.540541
6     G  0.833333

In [ ]:
df1 = pd.concat([df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].count(),
                 df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].mean()], axis = 1)

In [ ]:
df1

  grade  good_bad grade  good_bad
0     A       296     A  0.885135
1     B       469     B  0.867804
2     C       304     C  0.812500
3     D       189     D  0.740741
4     E       101     E  0.732673
5     F        37     F  0.540541
6     G         6     G  0.833333

In [ ]:
df1 = df1.iloc[: , [0, 1, 3]]
df1

  grade  good_bad  good_bad
0     A       296  0.885135
1     B       469  0.867804
2     C       304  0.812500
3     D       189  0.740741
4     E       101  0.732673
5     F        37  0.540541
6     G         6  0.833333

In [ ]:
df1.columns = [df1.columns.values[0], 'n_obs', 'prop_good']
df1

  grade  n_obs  prop_good
0     A    296   0.885135
1     B    469   0.867804
2     C    304   0.812500
3     D    189   0.740741
4     E    101   0.732673
5     F     37   0.540541
6     G      6   0.833333

In [ ]:
df1['prop_n_obs'] = df1['n_obs'] / df1['n_obs'].sum()
df1

  grade  n_obs  prop_good  prop_n_obs
0     A    296   0.885135    0.211127
1     B    469   0.867804    0.334522
2     C    304   0.812500    0.216833
3     D    189   0.740741    0.134807
4     E    101   0.732673    0.072040
5     F     37   0.540541    0.026391
6     G      6   0.833333    0.004280

In [ ]:
df1['n_good'] = df1['prop_good'] * df1['n_obs']
df1['n_bad'] = (1 - df1['prop_good']) * df1['n_obs']
df1

  grade  n_obs  prop_good  prop_n_obs  n_good  n_bad
0     A    296   0.885135    0.211127   262.0   34.0
1     B    469   0.867804    0.334522   407.0   62.0
2     C    304   0.812500    0.216833   247.0   57.0
3     D    189   0.740741    0.134807   140.0   49.0
4     E    101   0.732673    0.072040    74.0   27.0
5     F     37   0.540541    0.026391    20.0   17.0
6     G      6   0.833333    0.004280     5.0    1.0

In [ ]:
df1['prop_n_good'] = df1['n_good'] / df1['n_good'].sum()

In [ ]:
df1['prop_n_bad'] = df1['n_bad'] / df1['n_bad'].sum()
df1

  grade  n_obs  prop_good  prop_n_obs  n_good  n_bad  prop_n_good  prop_n_bad
0     A    296   0.885135    0.211127   262.0   34.0     0.226840    0.137652
1     B    469   0.867804    0.334522   407.0   62.0     0.352381    0.251012
2     C    304   0.812500    0.216833   247.0   57.0     0.213853    0.230769
3     D    189   0.740741    0.134807   140.0   49.0     0.121212    0.198381
4     E    101   0.732673    0.072040    74.0   27.0     0.064069    0.109312
5     F     37   0.540541    0.026391    20.0   17.0     0.017316    0.068826
6     G      6   0.833333    0.004280     5.0    1.0     0.004329    0.004049

In [ ]:
df1['WoE'] = np.log(df1['prop_n_good'] / df1['prop_n_bad'])
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE
0,A,296,0.885135,0.211127,262.0,34.0,0.226840,0.137652,0.499517
1,B,469,0.867804,0.334522,407.0,62.0,0.352381,0.251012,0.339212
2,C,304,0.812500,0.216833,247.0,57.0,0.213853,0.230769,-0.076130
3,D,189,0.740741,0.134807,140.0,49.0,0.121212,0.198381,-0.492645
4,E,101,0.732673,0.072040,74.0,27.0,0.064069,0.109312,-0.534239
5,F,37,0.540541,0.026391,20.0,17.0,0.017316,0.068826,-1.379948
6,G,6,0.833333,0.004280,5.0,1.0,0.004329,0.004049,0.066971

In [ ]:
df1 = df1.sort_values(['WoE'])
df1 = df1.reset_index(drop = True)
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE
0,F,37,0.540541,0.026391,20.0,17.0,0.017316,0.068826,-1.379948
1,E,101,0.732673,0.072040,74.0,27.0,0.064069,0.109312,-0.534239
2,D,189,0.740741,0.134807,140.0,49.0,0.121212,0.198381,-0.492645
3,C,304,0.812500,0.216833,247.0,57.0,0.213853,0.230769,-0.076130
4,G,6,0.833333,0.004280,5.0,1.0,0.004329,0.004049,0.066971
5,B,469,0.867804,0.334522,407.0,62.0,0.352381,0.251012,0.339212
6,A,296,0.885135,0.211127,262.0,34.0,0.226840,0.137652,0.499517

In [ ]:
df1['diff_prop_good'] = df1['prop_good'].diff().abs()
df1['diff_WoE'] = df1['WoE'].diff().abs()
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE
0,F,37,0.540541,0.026391,20.0,17.0,0.017316,0.068826,-1.379948,NaN,NaN
1,E,101,0.732673,0.072040,74.0,27.0,0.064069,0.109312,-0.534239,0.192133,0.845709
2,D,189,0.740741,0.134807,140.0,49.0,0.121212,0.198381,-0.492645,0.008067,0.041594
3,C,304,0.812500,0.216833,247.0,57.0,0.213853,0.230769,-0.076130,0.071759,0.416515
4,G,6,0.833333,0.004280,5.0,1.0,0.004329,0.004049,0.066971,0.020833,0.143101
5,B,469,0.867804,0.334522,407.0,62.0,0.352381,0.251012,0.339212,0.034471,0.272241
6,A,296,0.885135,0.211127,262.0,34.0,0.226840,0.137652,0.499517,0.017331,0.160305

In [ ]:
df1['IV'] = (df1['prop_n_good'] - df1['prop_n_bad']) * df1['WoE']
df1['IV'] = df1['IV'].sum()
df1

,grade,n_obs,prop_good,prop_n_obs,n_good,n_bad,prop_n_good,prop_n_bad,WoE,diff_prop_good,diff_WoE,IV
0,F,37,0.540541,0.026391,20.0,17.0,0.017316,0.068826,-1.379948,NaN,NaN,0.213511
1,E,101,0.732673,0.072040,74.0,27.0,0.064069,0.109312,-0.534239,0.192133,0.845709,0.213511
2,D,189,0.740741,0.134807,140.0,49.0,0.121212,0.198381,-0.492645,0.008067,0.041594,0.213511
3,C,304,0.812500,0.216833,247.0,57.0,0.213853,0.230769,-0.076130,0.071759,0.416515,0.213511
4,G,6,0.833333,0.004280,5.0,1.0,0.004329,0.004049,0.066971,0.020833,0.143101,0.213511
5,B,469,0.867804,0.334522,407.0,62.0,0.352381,0.251012,0.339212,0.034471,0.272241,0.213511
6,A,296,0.885135,0.211127,262.0,34.0,0.226840,0.137652,0.499517,0.017331,0.160305,0.213511

Pre-Processing Discrete Variables: Automating Calculations

In [ ]:
def woe_discrete(df, discrete_variable_name, good_bad_variable_df):
  df = pd.concat([df[discrete_variable_name], good_bad_variable_df], axis = 1)
  df1 = pd.concat([df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].count(),
                 df1.groupby(df1.columns.values[0], as_index = False)[df1.columns.values[1]].mean()], axis = 1)
  df = df.iloc[:, [0, 1, 3]]
  df.columns = [df.columns.values[0], 'n_obs', 'prop_good']
  df['prop_n_obs'] = df['n_obs'] / df['n_obs'].sum()
  df['n_good'] = df['prop_good'] * df['n_obs']
  df['n_bad'] = df['prop_bad'] * df['n_obs']
  df['prop_n_good'] = df['n_good'] / df['n_good'].sum()
  df['prop_n_bad'] = df['n_bad'] / df['n_bad'].sum()
  df['WoE'] = np.log(df['prop_n_good'] / df['prop_n_bad'])
  df = df.sort_values()